### ISSUE TITLE
Improve GetAll Topics Query In optimized way

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#159]
Improve the getAll Topic query in optimized way, 
This may include the queries for getAll topics on main page of the site.

- In Get All API:
    - If as of date is today:
        - Update the logic to get the latest version of a tree/topic from mongo, rather than fetching the trees/topics for today
    - If as of date is less than today:
        - Get the result from MySQL
        - Limitation: The trees will not be sorted by score

**Comment by sajid315** [comment]
Improve the getAll Topic query in optimized way, 
This may include both sides as Database and MonogDb.

**Comment by sajid315** [comment]
Needs discussion when jobs are stopped. Should we need to go for database in this scenario.

**Comment by sajid315** [comment]
Linked with #151 , Verified by Rupali.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
