### ISSUE TITLE
Verify the responses for the topics API

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#162]
Verify the getAll API responses after optimization:
1- Filters
2- Namespaces
3- Browse Pages
4- As Of filters.
5- Algorithm bases.

**Comment by sajid315** [comment]
Linked with https://github.com/the-canonizer/canonizer-service/issues/151 , Verified by Rupali.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
