### ISSUE TITLE
Throw proper exceptions for Topics API

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#163]
Implement the flow for throwing the proper exceptions to frontend:
1- In case of mongodb failure.
2- In case of database failues.
3- In case of DB drivers. 
4- And for the other common scenarios.

**Comment by sajid315** [comment]
Linked with https://github.com/the-canonizer/canonizer-service/issues/151 , Verified by Rupali.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
