### ISSUE TITLE
Update the filter "Only My topics" in service performance

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#166]
Update the only my topics changes according to last updates for ticket fixing.
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/101

**Comment by sajid315** [comment]
Linked with https://github.com/the-canonizer/canonizer-service/issues/151 , Verified by Rupali.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
