### ISSUE TITLE
Make a cron job to remove trees other than latest

### ISSUE THREAD

**Issue by M-Darab** [the-canonizer/canonizer-service#168]
Rather than removing all trees before 30 days, A Cron Job should remove all older versions of each topic tree and keep the latest one (even if the latest version is 100 or more days old)

**Comment by sajid315** [comment]
I need to review this functionality by making more version of tree date wise.

**Comment by sajid315** [comment]
Scheduled command tested for multiple versions of tree. Also the scheduler time updated to daily for this new command.

**Comment by sajid315** [comment]
Linked with https://github.com/the-canonizer/canonizer-service/issues/151 , Verified by Rupali.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
