### ISSUE TITLE
MongoDb Get API Score Bugs

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#174]
In case of get API after changes of MongoDB structure.
If the payload consist on older date than today. 
Get API ll make new cache in MongoDB. 

**Problem:** On get API for older date , all scores getting as 0.

**Comment by sajid315** [comment]
Verified the scores getting 0 , now scores are showing fine on local. 
Ticket related to enhancement and will b deploy on staging with complete enhancement code.

**Comment by sajid315** [comment]
Linked with https://github.com/the-canonizer/canonizer-service/issues/151 , Verified by Rupali.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
