### ISSUE TITLE
Canonizer Service Performance Bug-QA

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#178]
Case # 1

- Create topic

- Add multiple camps and add support by user 1

Actual Result : Scores are getting "Zero" in tree camps after adding support

Expected Result: Score must be updated without page refresh

![Image](https://user-images.githubusercontent.com/120023458/214246905-8537a86a-0bc1-46c4-8327-2ddfc647b85e.png)

Case # 2

- On remove support from topic detail pages scores must be updated

**Comment by sajid315** [comment]
Tested and verified. QA needs final testing.

**Comment by hassaanCD** [comment]
fixed

**Comment by hassaanCD** [comment]
Tested and is working on production
