### ISSUE TITLE
Empty tree bug-QA

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#179]
Steps to Reproduce: 

- Create topic

- Add multiple camps and add support by user 1

Expected Result: Tree must be shown

![Image](https://user-images.githubusercontent.com/120023458/214248170-1150dd62-596d-4239-9631-fba51293d980.png)

**Comment by M-Darab** [comment]
Unfortunately Empty tree issue is not occurring again, seems like this is the issue in rare cases. I'll take a look for this issue again after [178](https://github.com/the-canonizer/canonizer-service/issues/178), might be this screenshot linked with some sort of issue in [178](https://github.com/the-canonizer/canonizer-service/issues/178) ticket.

**Comment by rupalichavan9860** [comment]
Closing this since a related ticket is available.

**Comment by hassaanCD** [comment]
As this ticket is linked to ticket #178 which is fixed and working fine on production so we can close this ticket.
