### ISSUE TITLE
Removing support from camp cause increase in tree score on staging

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#184]
Steps to reproduce:

1. Create new topic
2. Add camp01 and add support to it
3. Add subcamp01 and add support to it
4. Add camp02 and add support to it
5. Add subcamp02 and add support to it
6. Add camp03 and add support to it
7. Remove support from camp03

Actual Result: 

1. Both "Remove your support" and "Directly Join and Support" button active
2. Score increased to 1.5

![Image](https://user-images.githubusercontent.com/120023458/215790146-94e6c125-b7b4-4398-991a-a7790a14937e.png)

![Image](https://user-images.githubusercontent.com/120023458/215790215-5477f9bc-f6d7-4e60-a361-d88bbfbb7bcc.png)

**Comment by sajid315** [comment]
PR Raised and verified on local, 
https://github.com/the-canonizer/canonizer-3.0-api/pull/550

**Comment by hassaanCD** [comment]
fixed

![f3](https://user-images.githubusercontent.com/120023458/221859121-d3f84921-d2d7-4eed-b5f7-57144e1fd197.png)

**Comment by rupalichavan9860** [comment]
Verified on live
