### ISSUE TITLE
Score first increase to "1.5" and then become "0" after page refresh on staging

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#188]
Steps to reproduce:

Create new topic
Add camp01 and add support to it
Add subcamp01 and add support to it
Remove support from subcamp01

Actual Result:

Case 1:
Tree Score increased to "1.5"
Case 2:
Score become "0" after page refresh

![Image](https://user-images.githubusercontent.com/120023458/216545879-510874bd-c7c7-4db1-80cb-dfa195e0396d.png)

![Image](https://user-images.githubusercontent.com/120023458/216545963-c811f21d-6d15-4f11-b1a9-9ba6561da0c1.png)

**Comment by saniatg** [comment]
@rupalichavan9860 @hassaanCD tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
