### ISSUE TITLE
100% score is not showing in some cases

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#225]
As shown in attached screenshots:

Score before checking 100% score checkbox

![Image](https://user-images.githubusercontent.com/120023458/243294198-f8c6de8d-a04d-4eb9-b9b6-a92562187504.png)

Score after checking 100% score checkbox

![Image](https://user-images.githubusercontent.com/120023458/243294303-533fd1c8-469c-492e-8fdd-4b059bfab9fc.png)

**Comment by rupalichavan9860** [comment]
Not an issue
