### ISSUE TITLE
Timeline event links for older camps including wrong camp numbers.

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#237]
Steps to Reproduce:
Navigate to link 
https://canonizer3.canonizer.com/eventline/23-Hard-Problem/15-Mind-Brain-Identity
Move Event bar to the end
Search for "Mind Brain Identity" in "Events"
Below is the error, here "696" is wrong camp number. It should consist on right camp-number with camp name.
![Image](https://github.com/the-canonizer/canonizer-service/assets/120023458/5b665a31-566f-4652-959b-42dd111c3510)

**Comment by sunilspr7** [comment]
"event": {
      "message": "Sunil_spr created a new Camp c2",
      "type": "create_camp",
      "id": 4583,
      "old_parent_id": null,
      "new_parent_id": null,
      "nickname_id": 650,
      "url": "https://localhost:8000/topic/864-demo-703-up/3-c2"
    },
    
    @shahab-ramzan  I have pass "url" variable in event.
