### ISSUE TITLE
GetAll API Performance by time and data

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#248]
Make Impact Analysis to get ALL API Response time, 
- We can utilize the staging database for analysis.
- Local DB for analysis. 
- Comparison b/w the results.
- Finding and implementing the origins to improve MongoDB query results.

**Comment by array-junkie** [comment]
## Mongo DB Optimization

### Before Optimization
- MongoDB: 432 ms

## Initial Review
- Get staging database from @akuks and import on local machine
- Create 130K+ mongo trees from database
- Calculate each mongo aggregate query stage execution time.
- Apply single key indexing for better performance and low response time of $match and $sort. It reduced the time arround **50ms** to **70ms** from the above time

## Final Approach
- Apply composite indexing on algorithm_id and as_of_date. It reduces the time arround **100ms** to **130ms** from the current time.
- Reorder the mongo aggregate query stages for better performance and low response time.
- Reduce page count query. It reduces the time upto **250ms** or less.

### After Optimization
- MongoDB: 223 ms

_Note: After the deployment of this ticket, we will observe the response time of mongo for further analysis on staging._

**Comment by sajid315** [comment]
@akashgit77 

As per discussion in call you have to write Selenium test case for browse page pagination button to check whether the API is responds successfully on each call when we run automated test cases.

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-service/assets/105647543/f38486b3-3761-4ced-893a-96a94865a381)

@sajid315 when we are clicking on "load more" two topics with same name were visible.I have created separate ticket #1264 for this issue.Remaining pagination is working fine.
