### ISSUE TITLE
GetAll API: Same response in both mongo and database case.

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-service#250]
## Canonizer
Make response same in case of mongo and database.

### MongoDB Case
![Image](https://github.com/the-canonizer/canonizer-service/assets/100785013/6cf018f3-3bf0-4fd4-b9cf-ece471515eb3)

### Database Case
![Image](https://github.com/the-canonizer/canonizer-service/assets/100785013/a0778ce4-f006-4d4f-8944-ddf32ec034c8)

**Comment by array-junkie** [comment]
I am writing unit test cases to check the response in the case of DB and Mongo should be same.

**Comment by subhancd** [comment]
fixed. verified on development server
