### ISSUE TITLE
Topic listing is not showing on development server

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#289]
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-service/assets/120023458/e8a49b6d-a17d-44f5-894e-92cc11434e83)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1569

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1569

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by saniatg** [comment]
working fine on production
