### ISSUE TITLE
Camps not opening only my topics, AsOfDate listing getting error -- Canonizer Live

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-service#296]
On Canonizer Production: 
1- Listing topics not opening in case of "Only my topics".

![Image](https://github.com/the-canonizer/canonizer-service/assets/111273633/684051c2-a36e-4086-b17b-b898a352fe55)

2- Listing getting 500 "Internal Server Error" on asOfDate. 

![Image](https://github.com/the-canonizer/canonizer-service/assets/111273633/61f3990b-70cb-414f-9bf5-8286b6e0ebc2)

**Comment by saniatg** [comment]
working  fine on development and live

**Comment by saniatg** [comment]
working fine on production
