### ISSUE TITLE
Not able to add "Nickname" on live

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#305]
As shown in attached screenshot

![Image](https://github.com/the-canonizer/canonizer-service/assets/120023458/83a19e90-0374-4d63-adb2-64c6f625282b)

**Comment by array-junkie** [comment]
This issue occurred due to a code conflict on the production. The code was partially deployed on the production. This issue is resolved as the complete code is deployed on the production.

**Comment by saniatg** [comment]
working fine on development and live

**Comment by hassaanCD** [comment]
Working fine on production
