### ISSUE TITLE
Camp Leader Functionality: Info message confusion in Sign Camp pop-up

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-service#308]
Steps to Reproduce:
Login with User A and create topic
Create camp under this topic and add "Direct Support"
Click on "Sign" button and observe info message in "Sign Camp" pop Up

As User A is the only supporter of a camp then the info message "There is no camp leader of this camp C1. If you continue, the oldest direct supporter ("Andrea_Allsop") will assigned as new camp leader and your support will be delegated to the camp leader" must be changed.

Expected Result: 
Why showing "name" if User A is the only supporter. 
If there is only single "User A" then why word "oldest" is used in this case.

![Image](https://github.com/the-canonizer/canonizer-service/assets/120023458/03b9dd23-3356-41c8-8dd2-9600b5de897d)

Also the camp name "C1" must be "bold" or "clickable" as in all other pop-ups in whole application

**Comment by sajid315** [comment]
Following change has been pushed to the ticket. 
https://github.com/the-canonizer/canonizer-3.0-api/commit/13394fe0689eb939feab48cc38377aae6a4ac03a

**Comment by sajid315** [comment]
Fixing related to showing camp names and nicknames as bold, 
https://github.com/the-canonizer/canonizer-3.0-api/commit/982f010f8b0cfdac4712350a12c044a23757101a

@wahaj-hafeez in this above requirement to display Info and Warning messages from the front-end side you have to render the HTML directly in the pop up so in this regard we need update from frontend side. 
Please have a look into it and then you can move this ticket ahead.

**Comment by DevAlchemyCD** [comment]
Commit : https://github.com/the-canonizer/canonizer-3.0-frontend/commit/a8fd1265aa0e7804936193295618ee6103ef1dcb

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
