### ISSUE TITLE
Camp leader - issue with score count and with the button

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-service#319]
Steps:

1.  Create a topic and remove support from agreement
2. Click on sign button
3. Now score is 1 and user is assigned as camp leader
4. Directly join button is seen click on it

Actual result -Score becomes 0.5
Expected- Directly join button must not be seen instead "Mange support must be seen" and support should be 1

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1788

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
